/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  BaseContract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import { TypedEventFilter, TypedEvent, TypedListener } from "./commons";

interface MarketInterface extends ethers.utils.Interface {
  functions: {
    "supply(uint256,uint256)": FunctionFragment;
    "trade(uint256)": FunctionFragment;
    "xToken()": FunctionFragment;
    "yToken()": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "supply",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "trade", values: [BigNumberish]): string;
  encodeFunctionData(functionFragment: "xToken", values?: undefined): string;
  encodeFunctionData(functionFragment: "yToken", values?: undefined): string;

  decodeFunctionResult(functionFragment: "supply", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "trade", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "xToken", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "yToken", data: BytesLike): Result;

  events: {
    "Supply(uint256,uint256)": EventFragment;
    "Trade(uint256)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "Supply"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "Trade"): EventFragment;
}

export class Market extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: MarketInterface;

  functions: {
    supply(
      _xAmount: BigNumberish,
      _yAmount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    trade(
      _xAmount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    xToken(overrides?: CallOverrides): Promise<[string]>;

    yToken(overrides?: CallOverrides): Promise<[string]>;
  };

  supply(
    _xAmount: BigNumberish,
    _yAmount: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  trade(
    _xAmount: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  xToken(overrides?: CallOverrides): Promise<string>;

  yToken(overrides?: CallOverrides): Promise<string>;

  callStatic: {
    supply(
      _xAmount: BigNumberish,
      _yAmount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    trade(_xAmount: BigNumberish, overrides?: CallOverrides): Promise<void>;

    xToken(overrides?: CallOverrides): Promise<string>;

    yToken(overrides?: CallOverrides): Promise<string>;
  };

  filters: {
    Supply(
      undefined?: null,
      undefined?: null
    ): TypedEventFilter<
      [BigNumber, BigNumber],
      { arg0: BigNumber; arg1: BigNumber }
    >;

    Trade(undefined?: null): TypedEventFilter<[BigNumber], { arg0: BigNumber }>;
  };

  estimateGas: {
    supply(
      _xAmount: BigNumberish,
      _yAmount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    trade(
      _xAmount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    xToken(overrides?: CallOverrides): Promise<BigNumber>;

    yToken(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    supply(
      _xAmount: BigNumberish,
      _yAmount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    trade(
      _xAmount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    xToken(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    yToken(overrides?: CallOverrides): Promise<PopulatedTransaction>;
  };
}
